# Generated by Django 3.2.2 on 2021-05-14 09:56

from django.db import migrations, models
import nepali_datetime_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nepali_date', nepali_datetime_field.models.NepaliDateField()),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
